// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exercise-1/imports/city.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_exercise_2d1_2fimports_2fcity_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_exercise_2d1_2fimports_2fcity_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_exercise_2d1_2fimports_2fcity_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_exercise_2d1_2fimports_2fcity_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_exercise_2d1_2fimports_2fcity_2eproto;
class City;
struct CityDefaultTypeInternal;
extern CityDefaultTypeInternal _City_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::City* Arena::CreateMaybeMessage<::City>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class City final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:City) */ {
 public:
  inline City() : City(nullptr) {}
  ~City() override;
  explicit PROTOBUF_CONSTEXPR City(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  City(const City& from);
  City(City&& from) noexcept
    : City() {
    *this = ::std::move(from);
  }

  inline City& operator=(const City& from) {
    CopyFrom(from);
    return *this;
  }
  inline City& operator=(City&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const City& default_instance() {
    return *internal_default_instance();
  }
  static inline const City* internal_default_instance() {
    return reinterpret_cast<const City*>(
               &_City_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(City& a, City& b) {
    a.Swap(&b);
  }
  inline void Swap(City* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(City* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  City* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<City>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const City& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const City& from) {
    City::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(City* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "City";
  }
  protected:
  explicit City(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kZipCodeFieldNumber = 2,
    kCountryNameFieldNumber = 3,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string zip_code = 2;
  void clear_zip_code();
  const std::string& zip_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_zip_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_zip_code();
  PROTOBUF_NODISCARD std::string* release_zip_code();
  void set_allocated_zip_code(std::string* zip_code);
  private:
  const std::string& _internal_zip_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_zip_code(const std::string& value);
  std::string* _internal_mutable_zip_code();
  public:

  // string country_name = 3;
  void clear_country_name();
  const std::string& country_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_country_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_country_name();
  PROTOBUF_NODISCARD std::string* release_country_name();
  void set_allocated_country_name(std::string* country_name);
  private:
  const std::string& _internal_country_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_country_name(const std::string& value);
  std::string* _internal_mutable_country_name();
  public:

  // @@protoc_insertion_point(class_scope:City)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr zip_code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr country_name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_exercise_2d1_2fimports_2fcity_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// City

// string name = 1;
inline void City::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& City::name() const {
  // @@protoc_insertion_point(field_get:City.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void City::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:City.name)
}
inline std::string* City::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:City.name)
  return _s;
}
inline const std::string& City::_internal_name() const {
  return _impl_.name_.Get();
}
inline void City::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* City::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* City::release_name() {
  // @@protoc_insertion_point(field_release:City.name)
  return _impl_.name_.Release();
}
inline void City::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:City.name)
}

// string zip_code = 2;
inline void City::clear_zip_code() {
  _impl_.zip_code_.ClearToEmpty();
}
inline const std::string& City::zip_code() const {
  // @@protoc_insertion_point(field_get:City.zip_code)
  return _internal_zip_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void City::set_zip_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.zip_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:City.zip_code)
}
inline std::string* City::mutable_zip_code() {
  std::string* _s = _internal_mutable_zip_code();
  // @@protoc_insertion_point(field_mutable:City.zip_code)
  return _s;
}
inline const std::string& City::_internal_zip_code() const {
  return _impl_.zip_code_.Get();
}
inline void City::_internal_set_zip_code(const std::string& value) {
  
  _impl_.zip_code_.Set(value, GetArenaForAllocation());
}
inline std::string* City::_internal_mutable_zip_code() {
  
  return _impl_.zip_code_.Mutable(GetArenaForAllocation());
}
inline std::string* City::release_zip_code() {
  // @@protoc_insertion_point(field_release:City.zip_code)
  return _impl_.zip_code_.Release();
}
inline void City::set_allocated_zip_code(std::string* zip_code) {
  if (zip_code != nullptr) {
    
  } else {
    
  }
  _impl_.zip_code_.SetAllocated(zip_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.zip_code_.IsDefault()) {
    _impl_.zip_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:City.zip_code)
}

// string country_name = 3;
inline void City::clear_country_name() {
  _impl_.country_name_.ClearToEmpty();
}
inline const std::string& City::country_name() const {
  // @@protoc_insertion_point(field_get:City.country_name)
  return _internal_country_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void City::set_country_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.country_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:City.country_name)
}
inline std::string* City::mutable_country_name() {
  std::string* _s = _internal_mutable_country_name();
  // @@protoc_insertion_point(field_mutable:City.country_name)
  return _s;
}
inline const std::string& City::_internal_country_name() const {
  return _impl_.country_name_.Get();
}
inline void City::_internal_set_country_name(const std::string& value) {
  
  _impl_.country_name_.Set(value, GetArenaForAllocation());
}
inline std::string* City::_internal_mutable_country_name() {
  
  return _impl_.country_name_.Mutable(GetArenaForAllocation());
}
inline std::string* City::release_country_name() {
  // @@protoc_insertion_point(field_release:City.country_name)
  return _impl_.country_name_.Release();
}
inline void City::set_allocated_country_name(std::string* country_name) {
  if (country_name != nullptr) {
    
  } else {
    
  }
  _impl_.country_name_.SetAllocated(country_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.country_name_.IsDefault()) {
    _impl_.country_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:City.country_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_exercise_2d1_2fimports_2fcity_2eproto
